#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Пер-сервисные X-Internal-Secret для контура vps-sso.
#
# Модель: у КАЖДОГО защищённого хоста свой собственный секрет, который не
# годится ни для какого другого хоста. Источник истины — secrets-gateway,
# имена ключей VPS_SSO_INTERNAL_SECRET_<SERVICE>. Карта host -> имя ключа
# лежит в config-store (defaults/sso_internal_secrets) — значений там нет.
#
# nginx получает значения ОДНОЙ генерируемой картой map $host ->
# $vps_sso_internal_secret. Неизвестный host => пустая строка => nginx вообще
# не шлёт заголовок => vps-sso отвечает 403. Deny by default.
#
# Важное свойство: после перехода ни один vhost и ни один сниппет НЕ содержит
# значения секрета — только имя переменной. Именно закоммиченный vhost со
# значением и был каналом утечки в публичный репозиторий.
#
# ЗНАЧЕНИЯ НИКОГДА НЕ ПЕЧАТАЮТСЯ. Для сверки выводится только sha256_8 и длина.
# ---------------------------------------------------------------------------
set -euo pipefail

SECGW="${SECGW_URL:-http://100.66.108.118:8783}"
MAP_FILE="${SSO_MAP_FILE:-/etc/nginx/conf.d/00-vps-sso-internal-secrets.conf}"
PREFIX=VPS_SSO_INTERNAL_SECRET_
SITES=/etc/nginx/sites-enabled

if [ -z "${MESH_TOKEN:-}" ]; then
  set -a; . /root/vps-sso/.env 2>/dev/null || true; set +a
fi
MT="${MESH_TOKEN:-}"
[ -n "$MT" ] || { echo "FATAL: нет MESH_TOKEN для обращения к secrets-gateway" >&2; exit 1; }

# Защищённые хосты берём из ЖИВОГО nginx, а не из имён файлов: у сайта может
# быть алиас (langfuse.ibotz.fun == llm.ibotz.fun), и промах по алиасу означает
# молчаливый 403 на этом имени. Признак защищённости — собственный
# `location = /sso-auth` либо include любого из сниппетов vps-sso-auth* (есть
# вариант -api.conf для machine-vhost: по шаблону с ".conf" он НЕ ловился). Сам vhost sso.ibotz.fun
# под это НЕ подходит и в список не попадает, что и требуется.
hosts() {
  grep -RIl -e 'location = /sso-auth' -e 'vps-sso-auth' "$SITES" 2>/dev/null \
  | while read -r f; do
      grep -h '^[[:space:]]*server_name' "$f" | tr -d ';' | sed 's/^[[:space:]]*server_name[[:space:]]*//'
    done | tr ' ' '\n' | grep -v '^$' | sort -u
}

keyname() { printf '%s%s\n' "$PREFIX" "$(printf %s "$1" | sed 's/\.ibotz\.fun$//' | tr 'a-z.-' 'A-Z__')"; }

sha8() { printf %s "$1" | sha256sum | cut -c1-8; }

get_secret() {
  curl -fsS -m 8 -H "Authorization: Bearer $MT" "$SECGW/secrets/$1" 2>/dev/null \
    | python3 -c 'import sys,json;print(json.load(sys.stdin).get("value") or "")' 2>/dev/null || true
}

put_secret() {  # $1=key $2=value
  python3 - "$1" "$2" "$SECGW" "$MT" <<'PY'
import json, sys, urllib.request
key, value, secgw, mt = sys.argv[1:5]
body = json.dumps({"value": value, "note": "vps-sso per-service X-Internal-Secret"}).encode()
req = urllib.request.Request(f"{secgw}/secrets/{key}", data=body, method="PUT",
                             headers={"Authorization": f"Bearer {mt}",
                                      "Content-Type": "application/json"})
urllib.request.urlopen(req, timeout=10).read()
PY
}

cmd_hosts() { hosts; }

# Создать недостающие секреты. ИДЕМПОТЕНТНО: существующий ключ не трогаем —
# перегенерация втихую рассинхронизировала бы nginx и vps-sso.
cmd_provision() {
  local created=0 kept=0 h k cur v
  while read -r h; do
    [ -n "$h" ] || continue
    k=$(keyname "$h")
    cur=$(get_secret "$k")
    if [ -n "$cur" ]; then
      kept=$((kept+1))
      printf '%-24s %-46s kept    len=%s sha8=%s\n' "$h" "$k" "${#cur}" "$(sha8 "$cur")"
    else
      v=$(openssl rand -hex 32)
      put_secret "$k" "$v"
      created=$((created+1))
      printf '%-24s %-46s CREATED len=%s sha8=%s\n' "$h" "$k" "${#v}" "$(sha8 "$v")"
    fi
  done < <(hosts)
  echo "--- создано=$created сохранено=$kept ---"
}

# Карта host -> имя ключа для config-store (значений тут нет).
cmd_map_json() {
  local h first=1
  printf '{'
  while read -r h; do
    [ -n "$h" ] || continue
    [ $first -eq 1 ] || printf ','
    first=0
    printf '"%s":"%s"' "$h" "$(keyname "$h")"
  done < <(hosts)
  printf '}\n'
}

# Отрендерить nginx-карту. Пишем атомарно и только если КАЖДЫЙ хост получил
# значение: полукарта означала бы молчаливый 403 на непокрытых именах.
cmd_render_map() {
  local tmp h k v
  tmp=$(mktemp); chmod 600 "$tmp"
  {
    echo "# GENERATED by tools/sso-internal-secrets.sh render-map — НЕ ПРАВИТЬ РУКАМИ."
    echo "# host -> его СОБСТВЕННЫЙ X-Internal-Secret (годен только для этого хоста)."
    echo "# Неизвестный host => \"\" => nginx не шлёт заголовок => vps-sso 403."
    echo "map \$host \$vps_sso_internal_secret {"
    echo "    default \"\";"
    while read -r h; do
      [ -n "$h" ] || continue
      k=$(keyname "$h")
      v=$(get_secret "$k")
      [ -n "$v" ] || { echo "FATAL: в secrets-gateway нет значения $k (host $h) — сперва provision" >&2; exit 1; }
      printf '    "%s" "%s";\n' "$h" "$v"
    done < <(hosts)
    echo "}"
  } > "$tmp"
  mv "$tmp" "$MAP_FILE"
  chmod 600 "$MAP_FILE"
  chown root:root "$MAP_FILE"
  echo "написан $MAP_FILE, хостов=$(grep -cE '^    \"' "$MAP_FILE")"
}

# Сверка: что в шлюзе против того, что реально лежит в карте nginx.
cmd_verify() {
  local h k v inmap rc=0
  while read -r h; do
    [ -n "$h" ] || continue
    k=$(keyname "$h")
    v=$(get_secret "$k")
    inmap=$(grep -E "^    \"$h\" " "$MAP_FILE" 2>/dev/null | sed -E 's/.*" "([^"]*)";/\1/' || true)
    if [ -z "$v" ]; then printf '%-24s %-46s НЕТ В ШЛЮЗЕ\n' "$h" "$k"; rc=1
    elif [ -z "$inmap" ]; then printf '%-24s %-46s НЕТ В КАРТЕ nginx\n' "$h" "$k"; rc=1
    elif [ "$v" != "$inmap" ]; then printf '%-24s %-46s РАСХОЖДЕНИЕ шлюз=%s карта=%s\n' "$h" "$k" "$(sha8 "$v")" "$(sha8 "$inmap")"; rc=1
    else printf '%-24s %-46s ok      sha8=%s\n' "$h" "$k" "$(sha8 "$v")"
    fi
  done < <(hosts)
  return $rc
}

case "${1:-}" in
  hosts)      cmd_hosts ;;
  provision)  cmd_provision ;;
  map-json)   cmd_map_json ;;
  render-map) cmd_render_map ;;
  verify)     cmd_verify ;;
  *) echo "usage: $0 {hosts|provision|map-json|render-map|verify}" >&2; exit 2 ;;
esac
